POST http://sshop.local/api/cart/product/5
Cookie: PHPSESSID=apmk79v72r034bbjg3oephnkpf

###
POST http://sshop.local/api/cart/product/8
Cookie: PHPSESSID=apmk79v72r034bbjg3oephnkpf

###
POST http://sshop.local/api/cart/product/3
Cookie: PHPSESSID=apmk79v72r034bbjg3oephnkpf

###
PATCH http://sshop.local/api/cart/products/3/2
Cookie: PHPSESSID=apmk79v72r034bbjg3oephnkpf

###

