POST http://sshop.local/api/cart/product/5/2
Cookie: PHPSESSID=q89c9c7jhntsq09jmvd50q07f8

###

GET http://sshop.local/api/cart/total
Cookie: PHPSESSID=apmk79v72r034bbjg3oephnkpf

###

GET http://sshop.local/api/cart
Cookie: PHPSESSID=q89c9c7jhntsq09jmvd50q07f8

###


