POST http://sshop.local/api/cart/product/5
Cookie: PHPSESSID=pj294r19f0k2odlo1na4gchth2

###
POST http://sshop.local/api/cart/product/8
Cookie: PHPSESSID=pj294r19f0k2odlo1na4gchth2

###
POST http://sshop.local/api/cart/product/3
Cookie: PHPSESSID=pj294r19f0k2odlo1na4gchth2

###
PATCH http://sshop.local/api/cart/products/3/2
Cookie: PHPSESSID=pj294r19f0k2odlo1na4gchth2

###

